/* eslint-disable @typescript-eslint/no-require-imports */
const mappings = require("../data/game-mappings.json") as GameMappingsFile;
/* eslint-enable @typescript-eslint/no-require-imports */

/**
 * Generated by scripts/generate-server-mappings.ts: the only place where Embark asset ids meet
 * site slugs (docs/Game-Data.md).
 */
export interface GameMappingsFile {
    schemaVersion: number;
    gameVersion: string | null;
    generatedFrom: string | null;
    /** asset id -> item slug (currencies included) */
    items: Record<string, string>;
    /** unlock (OnlineItem) asset id -> blueprint item and the item it unlocks */
    blueprintUnlocks: Record<string, { blueprintItemId: string; itemId: string }>;
    /** generator asset id -> bench level */
    benches: Record<string, { benchId: string; level: number }>;
    /** InventoryStructure asset id -> name */
    structures: Record<string, string>;
    augmentLoadouts: Record<string, {
        loadoutFrameAssetId: number;
        backpackSlots: number;
        quickUseSlots: number;
        safePocketSlots: number;
        auxiliarySlots: number;
        name?: string;
    }>;
    /**
     * quest asset id -> quest slug, objective node asset id -> objective key (as in
     * public/data/game/quests.json), `required` = amount of each leaf objective.
     */
    quests: Record<string, {
        questId: string;
        objectives: Record<string, string>;
        required: Record<string, number>;
    }>;
    /**
     * project / phase / step / goal asset id -> project slug and key ('i', 'i.j', 'i.j.k').
     * Projects carry `name`, steps `name`, goals `itemId` and `required` (display data for the
     * synced progress).
     */
    projects: Record<string, {
        projectId: string;
        key?: string;
        name?: string;
        itemId?: string;
        required?: number;
    }>;
    /** per slug kind: arctracker id -> slug, where they differ */
    arctracker: Record<string, Record<string, string>>;
    constants: {
        currencies: Record<string, number>;
        owners: Record<string, number>;
        stash: Record<string, number | number[]>;
        inventory: Record<string, number>;
    };
}

export const gameMappings: GameMappingsFile = mappings;
